In [1]:
%pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\munta\appdata\local\programs\python\python312\lib\site-packages (3.0.6)
Requirement already satisfied: openpyxl in c:\users\munta\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\munta\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\munta\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\munta\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: et-xmlfile in c:\users\munta\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\munta\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# Online Retail Sales & Customer Analysis

## Project Overview

This project analyzes online retail transaction data to identify sales trends, product performance, customer purchasing behavior, geographic patterns, cancellations, and repeat customer behavior.

The analysis demonstrates an end-to-end data analytics workflow using Python, Pandas, SQL, and Power BI.

### Dataset

**Source:** UCI Machine Learning Repository – Online Retail II

The dataset contains online retail transactions with information about invoices, products, quantities, prices, dates, customers, and countries.

### Tools Used

- Python
- Pandas
- SQL
- Power BI
- JupyterLab
- GitHub

### Business Questions

1. What is the total sales revenue?
2. Which products generate the highest revenue?
3. Which countries perform best?
4. How does revenue change over time?
5. Which customers generate the most revenue?
6. Which products have weak sales performance?
7. What is the cancellation rate?
8. How many customers are repeat customers?

## 1. Import and Load Data

In [2]:
import pandas as pd

df = pd.read_excel("online_retail_II.xlsx")

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

## 2. Understand the Data

In [3]:
df.shape

(525461, 8)

In [4]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

## 3. Data Quality Checks

In [6]:
df.duplicated().sum()

np.int64(6865)

In [7]:
df['Invoice'].astype(str).str.startswith('C').sum()

np.int64(10206)

In [8]:
(df['Quantity'] < 0).sum()

np.int64(12326)

In [9]:
(df['Price'] <= 0).sum()

np.int64(3690)

In [10]:
df[df['Price'] <= 0][['Invoice', 'StockCode', 'Description', 'Quantity', 'Price']].head(10)

     Invoice StockCode   Description  Quantity  Price
263   489464     21733  85123a mixed       -96    0.0
283   489463     71477         short      -240    0.0
284   489467    85123A   21733 mixed      -192    0.0
470   489521     21646           NaN       -50    0.0
3114  489655     20683           NaN       -44    0.0
3161  489659     21350           NaN       230    0.0
3162  489660     35956          lost     -1043    0.0
3168  489663    35605A       damages      -117    0.0
3731  489781     84292           NaN        17    0.0
4296  489806     18010           NaN      -770    0.0

In [11]:
df[['Invoice', 'StockCode', 'Description', 'Quantity', 'Price']].head(10)

  Invoice StockCode                          Description  Quantity  Price
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12   6.95
1  489434    79323P                   PINK CHERRY LIGHTS        12   6.75
2  489434    79323W                  WHITE CHERRY LIGHTS        12   6.75
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48   2.10
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24   1.25
5  489434     22064           PINK DOUGHNUT TRINKET POT         24   1.65
6  489434     21871                  SAVE THE PLANET MUG        24   1.25
7  489434     21523   FANCY FONT HOME SWEET HOME DOORMAT        10   5.95
8  489435     22350                            CAT BOWL         12   2.55
9  489435     22349       DOG BOWL , CHASING BALL DESIGN        12   3.75

In [12]:
df[df.duplicated(keep=False)].sort_values(
    ['Invoice', 'StockCode']
).head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom

## 4. Data Cleaning

In [13]:
df_clean = df.copy()

In [14]:
df_clean = df_clean.drop_duplicates()

In [15]:
df_clean.shape

(518596, 8)

In [16]:
df_clean['Customer ID'].isna().sum()

np.int64(107833)

In [17]:
df_clean['Description'].isna().sum()

np.int64(2928)

In [18]:
(df_clean['Quantity'] < 0).sum()

np.int64(12302)

In [19]:
df_clean[df_clean['Quantity'] < 0][
    ['Invoice', 'StockCode', 'Description', 'Quantity', 'Price', 'Customer ID', 'Country']
].head(10)

,Invoice,StockCode,Description,Quantity,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2.95,16321.0,Australia
183,C489449,21871,SAVE THE PLANET MUG,-12,1.25,16321.0,Australia
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,1.25,16321.0,Australia
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,0.85,16321.0,Australia
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,4.25,17592.0,United Kingdom

In [20]:
(
    (df_clean['Quantity'] < 0) &
    (df_clean['Invoice'].astype(str).str.startswith('C'))
).sum()

np.int64(10181)

In [21]:
df_clean[
    (df_clean['Quantity'] < 0) &
    (~df_clean['Invoice'].astype(str).str.startswith('C'))
][
    ['Invoice', 'StockCode', 'Description', 'Quantity', 'Price', 'Customer ID', 'Country']
].head(10)

,Invoice,StockCode,Description,Quantity,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,0.0,NaN,United Kingdom
283,489463,71477,short,-240,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,0.0,NaN,United Kingdom
4538,489820,21133,invcd as 84879?,-720,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,0.0,NaN,United Kingdom

## 5. Create Sales Dataset and Calculate Revenue

In [22]:
sales_df = df_clean[
    (df_clean['Quantity'] > 0) &
    (df_clean['Price'] > 0)
].copy()

In [23]:
sales_df.shape

(504731, 8)

In [24]:
sales_df['Revenue'] = sales_df['Quantity'] * sales_df['Price']

In [25]:
sales_df[['Quantity', 'Price', 'Revenue']].head(10)

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0
5        24   1.65     39.6
6        24   1.25     30.0
7        10   5.95     59.5
8        12   2.55     30.6
9        12   3.75     45.0

In [26]:
sales_df['Revenue'].describe()

count    504731.000000
mean         20.351705
std          91.510976
min           0.001000
25%           4.200000
50%          10.200000
75%          17.700000
max       25111.090000
Name: Revenue, dtype: float64

In [27]:
sales_df[
    ['Invoice', 'StockCode', 'Description', 'Quantity', 'Price', 'Revenue', 'Customer ID', 'Country']
].sort_values('Revenue', ascending=False).head(10)

,Invoice,StockCode,Description,Quantity,Price,Revenue,Customer ID,Country
241827,512771,M,Manual,1,25111.09,25111.09,NaN,United Kingdom
432176,530715,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,9360,1.69,15818.40,15838.0,United Kingdom
517955,537632,AMAZONFEE,AMAZON FEE,1,13541.33,13541.33,NaN,United Kingdom
135015,502265,M,Manual,1,10953.50,10953.50,NaN,United Kingdom
135013,502263,M,Manual,1,10953.50,10953.50,12918.0,United Kingdom
342147,522796,M,Manual,1,10468.80,10468.80,NaN,United Kingdom
372834,525399,M,Manual,1,10468.80,10468.80,NaN,United Kingdom
358639,524159,M,Manual,1,10468.80,10468.80,14063.0,United Kingdom
74356,496115,M,Manual,1,8985.60,8985.60,17949.0,United Kingdom
228042,511465,15044A,PINK PAPER PARASOL,3500,2.55,8925.00,18008.0,United Kingdom

In [28]:
sales_df[
    sales_df['Description'].astype(str).str.contains('Manual|AMAZONFEE', case=False, na=False)
][
    ['Invoice', 'StockCode', 'Description', 'Quantity', 'Price', 'Revenue']
].shape

(555, 6)

In [29]:
sales_df = sales_df[
    ~sales_df['Description'].astype(str).str.contains(
        'Manual|AMAZONFEE',
        case=False,
        na=False
    )
].copy()

In [30]:
sales_df.shape

(504176, 9)

In [31]:
sales_df[['Invoice', 'StockCode', 'Quantity', 'InvoiceDate', 'Price', 'Revenue', 'Country']].isna().sum()

Invoice        0
StockCode      0
Quantity       0
InvoiceDate    0
Price          0
Revenue        0
Country        0
dtype: int64

In [47]:
sales_df.to_csv("online_retail_sales_clean.csv", index=False)

In [33]:
sales_df.shape

(504176, 9)

## 6. Business Analysis

### Question 1: What is the total sales revenue?

In [34]:
sales_df['Revenue'].sum()

np.float64(10009172.804000001)

### Question 2: Which products generate the highest revenue?

In [35]:
top_products = (
    sales_df.groupby('Description')['Revenue']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_products

Description
REGENCY CAKESTAND 3 TIER               169912.76
WHITE HANGING HEART T-LIGHT HOLDER     160345.63
DOTCOM POSTAGE                         116408.71
ASSORTED COLOUR BIRD ORNAMENT           72890.19
PAPER CHAIN KIT 50'S CHRISTMAS          58127.30
JUMBO BAG RED RETROSPOT                 56480.46
PARTY BUNTING                           49664.12
POSTAGE                                 49477.54
ROTATING SILVER ANGELS T-LIGHT HLDR     47954.49
EDWARDIAN PARASOL NATURAL               36925.26
Name: Revenue, dtype: float64

In [36]:
product_sales = sales_df[
    ~sales_df['Description'].astype(str).str.contains(
        'POSTAGE|DOTCOM POSTAGE',
        case=False,
        na=False
    )
].copy()

top_products = (
    product_sales.groupby('Description')['Revenue']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_products

Description
REGENCY CAKESTAND 3 TIER               169912.76
WHITE HANGING HEART T-LIGHT HOLDER     160345.63
ASSORTED COLOUR BIRD ORNAMENT           72890.19
PAPER CHAIN KIT 50'S CHRISTMAS          58127.30
JUMBO BAG RED RETROSPOT                 56480.46
PARTY BUNTING                           49664.12
ROTATING SILVER ANGELS T-LIGHT HLDR     47954.49
EDWARDIAN PARASOL NATURAL               36925.26
JUMBO BAG STRAWBERRY                    36732.16
VINTAGE UNION JACK BUNTING              36023.71
Name: Revenue, dtype: float64

### Question 3: Which countries generate the most revenue?

In [37]:
country_sales = (
    sales_df.groupby('Country')['Revenue']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

country_sales

Country
United Kingdom    8601663.653
EIRE               364099.450
Netherlands        268587.670
Germany            201250.371
France             142082.440
Sweden              51752.310
Denmark             50906.850
Spain               46157.660
Switzerland         43921.390
Australia           30313.350
Name: Revenue, dtype: float64

### Question 4: How does revenue change over time?

In [38]:
sales_df['YearMonth'] = sales_df['InvoiceDate'].dt.to_period('M')

monthly_sales = (
    sales_df.groupby('YearMonth')['Revenue']
    .sum()
)

monthly_sales

YearMonth
2009-12     820246.560
2010-01     635533.942
2010-02     547305.196
2010-03     776030.641
2010-04     655504.642
2010-05     652620.040
2010-06     706357.740
2010-07     643390.210
2010-08     684520.000
2010-09     880612.741
2010-10    1109163.840
2010-11    1461357.622
2010-12     436529.630
Freq: M, Name: Revenue, dtype: float64

In [39]:
customer_df = sales_df.dropna(subset=['Customer ID']).copy()

customer_df.shape

(400496, 10)

### Question 5: Which customers generate the most revenue?

In [40]:
top_customers = (
    customer_df.groupby('Customer ID')['Revenue']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_customers

Customer ID
18102.0    349164.35
14646.0    248396.50
14156.0    188371.29
14911.0    144115.90
13694.0    131443.19
17511.0     84541.17
15061.0     83282.93
16684.0     80489.21
16754.0     65500.07
13089.0     57885.45
Name: Revenue, dtype: float64

In [41]:
product_performance = (
    product_sales.groupby('Description')
    .agg(
        Revenue=('Revenue', 'sum'),
        Units_Sold=('Quantity', 'sum'),
        Transactions=('Invoice', 'count')
    )
    .sort_values('Revenue')
)

product_performance.head(20)

                                     Revenue  Units_Sold  Transactions
Description
PADS TO MATCH ALL CUSHIONS             0.014          14            14
CHAMPAGNE TRAY BLANK CARD              0.380           2             2
HAPPY BIRTHDAY GINGER CAT CARD         0.380           2             1
PINK HEART CHRISTMAS DECORATION        0.380           1             1
SILICON CUBE 25W, BLUE                 0.420           1             1
CAT W SUNGLASSES BLANK CARD            0.760           4             1
OWLS CHARLOTTE BAG                     0.850           1             1
UBO-LIGHT TRIOBASE BLUE                0.850           1             1
BLUE WHITE PLASTIC RINGS LAMPSHADE     0.850           1             1
HAPPY BIRTHDAY CARD TEDDY/CAKE         0.950           5             2
FOLKART HEART CHRISTMAS DECORATIONS    1.250           1             1
WHITE SCANDINAVIAN HEART CHRISTMAS     1.250           1             1
HOLLYHOCK SQUARE HANDY TIN             1.250           1             1
LETTER "U" BLING KEY RING              1.250           1             1
A4 WALL TIDY RED FLOWERS               1.300           2             2
RED TOP SCANDINAVIAN HEART             1.520           4             2
SWALLOW SMALL TUBE MATCHES             1.650           1             1
CRYSTAL SMALL JEWELLED PHOTOFRAME      1.650           1             1
3 BIRDS CANVAS SCREEN                  1.650           1             1
S/3 ROSE GARDEN SCENT SQU CANDLE       1.650           1             1

### Question 6: Which products have weak sales performance?

In [42]:
weak_products = (
    product_performance[
        product_performance['Transactions'] >= 10
    ]
    .sort_values('Revenue')
    .head(10)
)

weak_products

                                    Revenue  Units_Sold  Transactions
Description
PADS TO MATCH ALL CUSHIONS            0.014          14            14
LETTER "V" BLING KEY RING            15.100          14            12
PINK CHRISTMAS TREE DECORATION       15.630          37            10
GREETING CARD, STICKY GORDON         15.760          76            10
GREETING CARD, BLACKPOOL ROCK        15.900          28            13
PINK HANGING GINGHAM EASTER HEN      16.800          40            12
LILAC GAUZE BUTTERFLY LAMPSHADE      18.480          44            12
BLUE ORGANDY ROUND LAMPSHADE W BEA   18.700          22            10
SPOTS ON RED BOOKCOVER TAPE          19.320          46            14
BLUE HANGING GINGHAM EASTER HEN      21.420          51            13

### Question 7: What is the cancellation rate?

In [43]:
cancellations = df_clean[
    df_clean['Invoice'].astype(str).str.startswith('C')
]

cancellations.shape

(10182, 8)

In [44]:
total_invoices = df_clean['Invoice'].nunique()

cancelled_invoices = cancellations['Invoice'].nunique()

cancellation_rate = (cancelled_invoices / total_invoices) * 100

total_invoices, cancelled_invoices, cancellation_rate

(28816, 4592, 15.935591338145475)

In [45]:
customer_orders = (
    customer_df.groupby('Customer ID')['Invoice']
    .nunique()
)

total_customers = customer_orders.nunique()

repeat_customers = (customer_orders > 1).sum()

repeat_customer_rate = (repeat_customers / total_customers) * 100

total_customers, repeat_customers, repeat_customer_rate

(64, np.int64(2880), np.float64(4500.0))

### Question 8: How many customers are repeat customers?

In [46]:
total_customers = customer_orders.index.nunique()

repeat_customers = (customer_orders > 1).sum()

repeat_customer_rate = (repeat_customers / total_customers) * 100

total_customers, repeat_customers, repeat_customer_rate

(4298, np.int64(2880), np.float64(67.00791065611912))